using AirPlaySender.Core.Receiving;
using Xunit;

namespace AirPlaySender.Core.Tests;

/// <summary>
/// <see cref="H264Sps.TryParseDimensions"/> against hand-built SPS
/// bitstreams with known field values, worked out bit-by-bit by hand (not
/// generated by an encoder, so the expected width/height are exact facts
/// about the input, not an assumption) — see the derivation in this
/// project's history for how each byte sequence below was constructed.
/// </summary>
public class H264SpsTests
{
    [Fact]
    public void ParsesA1280x720BaselineSpsWithNoCropping()
    {
        // profile_idc=66 (Baseline, skips the chroma/bit-depth/scaling branch),
        // pic_width_in_mbs_minus1=79 (=> 80*16=1280), pic_height_in_map_units_minus1=44
        // (=> 45*16=720, frame_mbs_only_flag=1), frame_cropping_flag=0.
        byte[] sps = Convert.FromHexString("6742001EF402802D80");

        bool ok = H264Sps.TryParseDimensions(sps, out int width, out int height);

        Assert.True(ok);
        Assert.Equal(1280, width);
        Assert.Equal(720, height);
    }

    [Fact]
    public void RefusesToGuessWhenACustomScalingMatrixIsPresent()
    {
        // profile_idc=100 (High) with seq_scaling_matrix_present_flag=1 —
        // deliberately out of scope (see H264Sps's class doc comment):
        // must report failure, not a wrong width/height.
        byte[] sps = Convert.FromHexString("6764001EAD");

        bool ok = H264Sps.TryParseDimensions(sps, out _, out _);

        Assert.False(ok);
    }

    [Fact]
    public void RejectsANonSpsNal()
    {
        byte[] notSps = [0x65, 0x01, 0x02, 0x03]; // NAL type 5 (IDR slice), not 7 (SPS)
        Assert.False(H264Sps.TryParseDimensions(notSps, out _, out _));
    }
}
